# Generated by Django 3.0 on 2020-01-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20200115_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
    ]
