# Generated by Django 3.0 on 2020-01-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userjifendetail',
            options={'verbose_name': '用户积分', 'verbose_name_plural': '用户积分'},
        ),
    ]
