# Generated by Django 3.0 on 2020-01-27 23:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0004_auto_20200127_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='JifenDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('zj', '注册'), ('jl', '奖励'), ('yq', '邀请'), ('cz', '充值')], default='zj', max_length=50, verbose_name='积分类别')),
                ('nums', models.IntegerField(default=0, verbose_name='积分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分明细',
                'verbose_name_plural': '积分明细',
            },
        ),
    ]
