# Generated by Django 3.0 on 2020-01-27 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_jifendetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserJifenDetail',
        ),
    ]
