# Generated by Django 3.0 on 2020-01-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_delete_userjifendetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jifendetail',
            name='type',
            field=models.CharField(choices=[('zj', '注册'), ('jl', '奖励'), ('yq', '邀请'), ('cz', '充值'), ('xf', '消费'), ('tk', '退款')], default='zj', max_length=50, verbose_name='积分类别'),
        ),
    ]
