# Generated by Django 3.0 on 2020-01-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='jifen',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
    ]
