# Generated by Django 3.0 on 2020-02-02 15:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JifenPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=100, verbose_name='充值编号')),
                ('trade_no', models.CharField(default='', max_length=100, verbose_name='支付订单号')),
                ('trade_type', models.CharField(choices=[('alipay', '支付宝'), ('webchat', '微信支付'), ('unipay', '银联支付')], max_length=10, verbose_name='支付方式')),
                ('subject', models.CharField(default='', max_length=100, verbose_name='商品名')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='交易金额')),
                ('desc', models.CharField(default='', max_length=500, verbose_name='商品说明')),
                ('status', models.CharField(choices=[('nopay', '未付款'), ('paied', '已付款'), ('faild', '失败')], max_length=10, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分充值',
                'verbose_name_plural': '积分充值',
            },
        ),
    ]
